<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= CONFIG_SITE_TITLE ?></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="./assets/css/main.css">
</head>

<body>
  <!-- HEADER -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="?page=home">
          <img src="./assets/img/3151589_bubble_chat_geek_message_icon.png" alt="Logo Geek" id="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link <?php if ($page === 'home') echo 'active'; ?>" href="?page=home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <?php if ($page === 'gallery') echo 'active'; ?>" href="?page=gallery">Gallery</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <?php if ($page === 'contact') echo 'active'; ?>" href="?page=contact">Contact</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <?php if ($auth::isRole("ROLE_ADMIN")) : ?>
                  <li><a class="dropdown-item" href="?page=admin">Admin</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                <?php endif; ?>
                <?php if (!isset($_SESSION['user'])) : ?>
                  <li><a class="dropdown-item" href="?page=login">Login</a></li>
                <?php else : ?>
                  <li><a class="dropdown-item" href="?page=profile">Profile</a></li>
                  <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
                <?php endif; ?>
              </ul>
            </li>

          </ul>
          <form class="d-flex">
            <input name="page" value="search" type="hidden">
            <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <!-- MAIN -->
  <main class="container-fluid">
    <?= $template ?>
    </main>
  <!-- FOOTER -->
  <!-- MODAL COOKIE -->
  <div class="modal" tabindex="-1" id="modalCookie">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal COOKIE</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Acceptez-vous les cookies ?</p>
      </div>
      <div class="modal-footer">
        <form method="POST">
        <button type="submit" name="cookie_no" class="btn btn-danger">No</button>
        <button type="submit" name="cookie_yes" class="btn btn-success">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>
  <footer class="bg-dark text-white text-center p-2">
    <p>&copy; CCI BEAUJOLAIS - DWWM</p>
    <?php if (isset($_SESSION['cookie'])):?>
    <?php if ((bool)$_SESSION['cookie']===true):?>
      Vous avez accepté les cookies
    <?php else: ?>
      Vous avez refusé les cookies
    <?php endif; ?>
    <br>
    <a href="javascript:modalCookieShow()" class="text-white">Révoquer mon choix de cookie</a>
    <?php endif; ?>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    const modalCookie = new bootstrap.Modal(document.getElementById('modalCookie'));
    <?php if ( !isset($_SESSION['cookie']) ) echo "modalCookie.show();"; ?>
    function modalCookieShow(){
      modalCookie.show();
    }
  </script>

</body>

</html>