<h1>Login</h1>
<section id="login">

<?php if (isset($errors) && !empty($errors)) : ?>
        <?php foreach ($errors as $error) : ?>
            <div class="alert alert-danger" role="alert">
                <?= $error ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

<?php if ( !isset($_SESSION['user']) ): ?>
<form method="POST" action="?page=login">
  <div class="mb-3">
    <label for="email" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Password</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>

  <!-- REMEMBER ME SI LES COOKIES SONT ACCEPTES -->
  <?php if (isset($_SESSION['cookie']) && ((bool)$_SESSION['cookie'])===true):?>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="remember_me" name="remember_me">
    <label class="form-check-label" for="remember_me">Remember Me</label>
  </div>
  <?php endif; ?>

  <button type="submit" class="btn btn-dark mb-3">Sign In</button>
</form>
<?php else : ?>
  <div class="alert alert-info" role="alert">
  Vous êtes déjà connecté avec le compte <?= $_SESSION['user']['email'] ?>.
  </div>
<?php endif; ?>
</section>