<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= CONFIG_SITE_TITLE ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #caroussel img{
            aspect-ratio: 16/10;
        }
    </style>
</head>
<body>
<!-- HEADER -->
<header>
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='home') echo "active"; ?>" aria-current="page" href="?page=home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='gallery') echo "active"; ?>" href="?page=gallery">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='contact') echo "active"; ?>" href="?page=contact" aria-expanded="false">
           Contact
          </a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
<!-- MAIN -->
<main class="container-fluid">
<?php include "./views/template_".$page.".phtml" ?>
</main>
<!-- FOOTER -->
<footer class="bg-dark text-white text-center p-2">
    <p>&copy; CCI BEAUJOLAIS - DWWM</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>