<h1>Search result(s) for <?= $keywords ?></h1>
<section id="search" class="row">
<?php foreach($posts as $article):?>
    <article class="col-12 col-sm-6 col-md-4 mb-3">
        <div class="card">
            <img src="<?= $article['image'] ?>" class="card-img-top" alt="<?= $article['title'] ?>">
            <div class="card-body">
                <h5 class="card-title"><?= $article['title'] ?></h5>
                <p class="card-text"><?= $article['description'] ?></p>
                <a href="#" class="btn btn-dark">Read more</a>
            </div>
        </div>
    </article>
<?php endforeach; ?>
</section>